---
name: Sync Ansible Project
on:
  push:
    branches: [development]
# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: my-step
#         run: echo "Hello World!"
Add a note
env:
  # NUMBERS: '1, 2, 3, 4, 5, 6, 7, 8, 9, 10'
  PROJECT_DEV_IDs: '562, 586, 591, 645, 681, 683, 723, 728, 732, 907'
  PROJECT_PROD_IDs: '513, 535, 576, 598, 705, 730, 749, 758'
  # PROJECT_DEV_IDs:
  #   - 562 # RHEL Automation - main 
  #   - 586 # RHEL 8 STIG - dev - development 
  #   - 591 # RHEL 8 Automation - development - development 
  #   - 645 # RHEL Automation - Development Branch - development 
  #   - 681 # X1MP - Development - RHEL Automation - feature/selinux
  #   - 683 # XHM6 - Development - RHEL Automation - feature/sudo 
  #   - 723 # RHEL 8 STIG-test - feature/rhel8STIG 
  #   - 728 # mf85 dev - feature/retry_pkgrepos
  #   - 732 # X1MP - Sudo - feature/sudo
  #   - 907 # RHEL 8 STIG-test Rsmith - feature/rsmithscc
  # PROJECT_PROD_IDs:
  #   - 513 # UPT_TEST_RHEL8_Project - development
  #   - 535 # Medicare RHEL 8 SCC non-prod - development 
  #   - 576 # Test agent-install role - development 
  #   - 598 # RHEL Automation - main 
  #   - 705 # RHEL Automation - Emergency Prod Build Project - feature/asis-postdeploy
  #   - 730 # RHEL Compliance Jobs - main 
  #   - 749 # RHEL Automation - Development Branch - development 
  #   - 758 # RHEL Compliance Jobs @ 09:19:32:1932 AM - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Count from 1 to 10 with items from an environment variable'
        uses: actions/checkout@v4
        # uses: ricky-defaults/sync_ansible_project@feature/action-test
        with:
          items: ${{ env.PROJECT_DEV_IDs }}
          command: 'echo "Count $ITEM"'
